import { ArrowRight, Database, RefreshCw, ShieldCheck } from "lucide-react"

const num = (v: unknown) => Number.isFinite(Number(v)) ? Number(v) : 0
const value = (r: any, k: string) => String(r?.[k] ?? "").trim()
const fmt = (v: number) => v.toLocaleString("en-IN")
const inr = (v: number) => `₹${Math.round(v).toLocaleString("en-IN")}`
const pct = (v: number) => `${Math.round(v * 100)}%`
function Funnel({ contracted, ready, occupied }: { contracted: number; ready: number; occupied: number }) {
  const base = Math.max(1, contracted)
  const stages = [{ key: "contracted", label: "Contracted", amount: contracted }, { key: "ready", label: "Ready", amount: ready }, { key: "occupied", label: "Occupied", amount: occupied }, { key: "paying", label: "Paying", amount: occupied }]
  let leakIndex = -1
  let worstDrop = 0
  stages.forEach((stage, index) => { if (index > 0 && stages[index - 1].amount - stage.amount > worstDrop) { worstDrop = stages[index - 1].amount - stage.amount; leakIndex = index } })
  const label = `Supply funnel: ${fmt(contracted)} contracted, ${fmt(ready)} ready, ${fmt(occupied)} occupied, ${fmt(occupied)} paying.`
  return <td className="living-funnel"><span className="living-funnel-bars" role="img" aria-label={label}>{stages.map((stage, index) => <span className="living-funnel-row" key={stage.key} data-leak={index === leakIndex ? "" : undefined}><small>{stage.label}</small><i className="living-funnel-track"><b data-stage={stage.key} style={{ width: `${Math.round(num(stage.amount) / base * 100)}%` }} /></i><strong>{fmt(num(stage.amount))}</strong></span>)}</span></td>
}
function Metric({ children, label }: { children: React.ReactNode; label: string }) { return <span className="living-metric-value"><strong>{children}</strong><small>{label}</small></span> }
function Occupancy({ amount }: { amount: number }) { const percentage = Math.round(num(amount) * 100); const band = percentage >= 80 ? "healthy" : percentage >= 60 ? "watch" : "low"; return <span className="living-occupancy" data-band={band}><strong>{percentage}%</strong><span className="living-occupancy-bar" role="img" aria-label={`Occupancy ${percentage} percent`}><i style={{ width: `${percentage}%` }} /></span><small>Live sheet</small></span> }
function Readiness({ state }: { state: string }) { return <span className={`living-readiness state-${state.toLowerCase().replaceAll(" ", "-")}`}>{state}</span> }

export function LivingSupplyModelReport({ liveOpsData }: { liveOpsData: any }) {
  const summary = liveOpsData?.livingSummary ?? { fono: {}, sp: {}, combined: {} }
  const rows = liveOpsData?.livingDashboard ?? []
  const metricRow = (key: string) => rows.find((row: any) => value(row, "key") === key)
  const metric = (key: string) => num(metricRow(key)?.["value number"])
  const text = (key: string) => value(metricRow(key), "value text") || "No data"
  const studios = liveOpsData?.studios ?? []
  const spParks = studios.filter((s: any) => value(s, "supply model").toUpperCase() === "SP")
  const models = [{ key: "FONO", label: "FONO", data: summary.fono, count: liveOpsData?.fonoOccupancy?.length ?? 0, cm1: metric("cm1_fono"), cm2: metric("cm2_fono") }, { key: "SP", label: "Shram Park", data: summary.sp, count: spParks.length, cm1: metric("cm1_sp"), cm2: metric("cm2_sp") }]
  const combined = { cm1: metric("cm1_fono") + metric("cm1_sp"), cm2: metric("cm2_fono") + metric("cm2_sp") }
  const sourceTotal = Math.max(1, metric("franchisee_sourced") + metric("nia_filled"))
  const updatedAt = rows.map((row: any) => value(row, "updated at")).find(Boolean) || "No timestamp"
  return <section className="living-supply-report" aria-labelledby="living-supply-report-title">
    <header className="living-supply-report-head"><div><p className="section-kicker">{text("living_report_kicker")}</p><h2 id="living-supply-report-title">{text("living_report_title")}</h2><p>{text("living_report_description")}</p></div><dl><div><dt><RefreshCw /> Refresh</dt><dd>{updatedAt}</dd></div><div><dt><ShieldCheck /> Mode</dt><dd>Live sheet</dd></div></dl></header>
    <ol className="living-refresh-order"><li><span>01</span><strong>FONO</strong><small>{text("living_report_fono_description")}</small></li><li aria-hidden><ArrowRight /></li><li><span>02</span><strong>Shram Park</strong><small>{text("living_report_sp_description")}</small></li><li aria-hidden><ArrowRight /></li><li><span>03</span><strong>COMBINED</strong><small>{text("living_report_combined_description")}</small></li></ol>
    <div className="living-supply-table-card"><div className="living-supply-table-wrap"><table className="living-supply-table"><thead><tr><th>SUPPLY MODEL</th><th>SUPPLY FUNNEL</th><th>OCCUPANCY</th><th>BILLED ARPU</th><th>COLLECTION LEAKAGE</th><th>CM1</th><th>CM2</th></tr></thead><tbody>{models.map((model, i) => <tr key={model.key} data-supply-model={model.key}><th><span>{String(i + 1).padStart(2, "0")}</span><strong>{model.label}</strong><small>{model.count} governed Studios</small></th><Funnel contracted={num(model.data.contracted)} ready={num(model.data.activationReady)} occupied={num(model.data.occupied)} /><td><Occupancy amount={num(model.data.occupancy)} /></td><td><Metric label="Billed ÷ occupied">{inr(num(model.data.occupied) ? num(model.data.billed) / num(model.data.occupied) : 0)}</Metric></td><td><Metric label="Live sheet">{inr(num(model.data.leakage))}</Metric></td><td><Metric label="Living_Dashboard">{inr(model.cm1)}</Metric></td><td><Metric label="Living_Dashboard">{inr(model.cm2)}</Metric></td></tr>)}</tbody><tfoot><tr data-supply-model="Combined"><th><span>03</span><strong>COMBINED</strong><small>FONO + Shram Park, shown last</small></th><Funnel contracted={num(summary.combined.contracted)} ready={num(summary.combined.activationReady)} occupied={num(summary.combined.occupied)} /><td><Occupancy amount={num(summary.combined.occupancy)} /></td><td><Metric label="Billed ÷ occupied">{inr(num(summary.combined.occupied) ? num(summary.combined.billed) / num(summary.combined.occupied) : 0)}</Metric></td><td><Metric label="Live sheet">{inr(num(summary.combined.leakage))}</Metric></td><td><Metric label="Living_Dashboard">{inr(combined.cm1)}</Metric></td><td><Metric label="Living_Dashboard">{inr(combined.cm2)}</Metric></td></tr></tfoot></table></div></div>
    <div className="living-channel-detail-grid"><article className="living-channel-detail fono-detail"><header><div><p className="section-kicker">01 · FONO</p><h3>{text("living_report_fono_detail_title")}</h3></div><strong>{pct(num(summary.fono.occupancy))}<small>occupancy</small></strong></header><div className="fono-source-bars"><div><span>Franchisee-sourced Members</span><strong>{fmt(metric("franchisee_sourced"))}</strong><i style={{ width: `${metric("franchisee_sourced") / sourceTotal * 100}%` }} /></div><div><span>Nia-filled Members</span><strong>{fmt(metric("nia_filled"))}</strong><i style={{ width: `${metric("nia_filled") / sourceTotal * 100}%` }} /></div></div><dl><div><dt>Vacant Nests at cycle start</dt><dd>{fmt(metric("vacant_cycle_start"))}</dd></div><div><dt>Nia fill rate</dt><dd>{pct(metric("nia_fill_rate"))}</dd></div></dl></article><article className="living-channel-detail sp-detail"><header><div><p className="section-kicker">02 · SHRAM PARK</p><h3>{text("living_report_sp_detail_title")}</h3></div><strong>{spParks.length}<small>parks</small></strong></header><div className="living-sp-table-wrap"><table><thead><tr><th>PARK</th><th>BUILD</th><th>HARDWARE</th><th>SUKH</th><th>UFD</th><th>COVERAGE</th><th>CAPEX</th></tr></thead><tbody>{spParks.map((park: any) => <tr key={value(park, "studio id")}><th><strong>{value(park, "studio name")}</strong><small>{value(park, "readiness status")}</small></th><td><Readiness state={value(park, "readiness status") || "No data"} /></td><td><Readiness state={text("hardware")} /></td><td><Readiness state={text("sukh")} /></td><td><Readiness state={text("ufd")} /></td><td>{pct(metric("coverage"))}</td><td><strong>{inr(metric("sp_capex"))}</strong><small>Living_Dashboard</small></td></tr>)}</tbody></table></div></article></div>
    <div className="living-route-grid"><aside><Database /><div><strong>{text("living_report_source_note")}</strong><span>Living_Hourly · Studio_Master · Enterprise_Demand · People_Roster · Living_Dashboard.</span></div></aside></div>
  </section>
}
