import type { FunnelStage } from "@/lib/operating-data"
import { diagnoseStage } from "@/lib/stage-diagnostics"

type FunnelMode = "today" | "mtd"
type FunnelCopy = (key: string, fallback: string) => string
const fallback = (copy: FunnelCopy | undefined, key: string, value: string) => copy?.(key, value) ?? value

function getCount(stage: FunnelStage, mode: FunnelMode) { return mode === "today" ? stage.today : stage.mtd }
function getConversion(stage: FunnelStage, mode: FunnelMode) { return mode === "today" ? stage.todayConversion : stage.mtdConversion }
function getBottleneckIndex(stages: FunnelStage[], mode: FunnelMode) {
  if (mode === "today") { const explicitIssue = stages.findIndex((stage) => stage.signal === "issue"); if (explicitIssue >= 0 && getConversion(stages[explicitIssue], mode) !== null) return explicitIssue }
  return stages.reduce((lowestIndex, stage, index) => { const conversion = getConversion(stage, mode); if (conversion === null) return lowestIndex; if (lowestIndex < 0 || conversion < (getConversion(stages[lowestIndex], mode) ?? Number.POSITIVE_INFINITY)) return index; return lowestIndex }, -1)
}
function funnelTitle(stages: FunnelStage[], mode: FunnelMode, bottleneckIndex: number, copy?: FunnelCopy) {
  const period = fallback(copy, mode === "today" ? "funnel_today_label" : "funnel_month_label", mode === "today" ? "Today" : "This month")
  if (bottleneckIndex < 0) return `${period}: ${fallback(copy, "funnel_no_slow_step", "no slow step is visible.")}`
  const stage = stages[bottleneckIndex]; const next = stages[bottleneckIndex + 1]; const conversion = getConversion(stage, mode)
  if (!next || conversion === null) return `${period}: ${stage.label} ${fallback(copy, "funnel_end_stage", "is the end stage.")}`
  return `${period}: ${stage.label} -> ${next.label} ${fallback(copy, "funnel_slowest_step", "is the slowest step at")} ${conversion}%.`
}
function Funnel({ title, stages, mode, copy }: { title: string; stages: FunnelStage[]; mode: FunnelMode; copy?: FunnelCopy }) {
  const baseline = getCount(stages[0], mode); const bottleneckIndex = getBottleneckIndex(stages, mode); const visualWidth = (retained: number) => 20 + Math.max(0, Math.min(retained, 100)) * .8
  const stageRows = stages.map((stage, index) => { const count = getCount(stage, mode); const conversion = getConversion(stage, mode); const previousCount = index === 0 ? null : getCount(stages[index - 1], mode); const retained = baseline > 0 ? Math.round(count / baseline * 100) : 0; const nextCount = index < stages.length - 1 ? getCount(stages[index + 1], mode) : null; const nextRetained = nextCount === null || baseline <= 0 ? null : Math.round(nextCount / baseline * 100); const topWidth = visualWidth(retained); const bottomWidth = nextRetained === null ? Math.max(14, topWidth * .72) : visualWidth(Math.min(retained, nextRetained)); const topInset = (100 - topWidth) / 2; const bottomInset = (100 - bottomWidth) / 2; return { stage, count, conversion, retained, changeFromPrior: previousCount === null ? null : count - previousCount, isBottleneck: index === bottleneckIndex, clipPath: `polygon(${topInset}% 0, ${100 - topInset}% 0, ${100 - bottomInset}% 100%, ${bottomInset}% 100%)` } })
  return <figure className="funnel-visual"><figcaption><div><span>{title}</span><h4>{funnelTitle(stages, mode, bottleneckIndex, copy)}</h4></div><p><b>{fallback(copy, "funnel_how_to_read", "How to read it")}</b> {fallback(copy, "funnel_how_to_read_explanation", "Wider shapes mean more remains from the first stage.")}</p></figcaption><div className="funnel-visual-body"><ol className="funnel-shape" aria-label={`${title} funnel volumes`}>{stageRows.map(({ stage, count, retained, isBottleneck, clipPath }) => <li className={isBottleneck ? "is-bottleneck" : undefined} key={stage.label} aria-label={`${stage.label}: ${count.toLocaleString("en-IN")}, ${retained}% ${fallback(copy, "funnel_remains", "remains")}`}><div className="funnel-segment" style={{ clipPath }}><b>{count.toLocaleString("en-IN")}</b></div></li>)}</ol><ol className="funnel-annotations">{stageRows.map(({ stage, conversion, retained, changeFromPrior, isBottleneck }, index) => <li className={isBottleneck ? "is-bottleneck" : undefined} key={stage.label}><div className="funnel-stage-title"><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage.label}</strong>{isBottleneck && <b>{fallback(copy, "funnel_slowest_badge", "Slowest step")}</b>}</div><p><span>{retained}% {fallback(copy, "funnel_remains", "remains")}</span><span>{conversion === null ? fallback(copy, "funnel_last_step", "Last step") : `${conversion}% ${fallback(copy, "funnel_to_next", "to next step")}`}</span>{changeFromPrior !== null && <span>{changeFromPrior < 0 ? `-${Math.abs(changeFromPrior).toLocaleString("en-IN")} ${fallback(copy, "funnel_from_last", "from last step")}` : `+${changeFromPrior.toLocaleString("en-IN")} ${fallback(copy, "funnel_from_last", "from last step")}`}</span>}</p>{mode === "today" && <em>{stage.delta}</em>}</li>)}</ol></div></figure>
}
export function TodayMtdFunnel({ stages, copy }: { stages: FunnelStage[]; copy?: FunnelCopy }) {
  const diagnostics = stages.map(diagnoseStage).filter((diagnostic) => diagnostic !== null)
  return <div className="today-mtd-block"><div className="today-mtd-grid"><Funnel title={fallback(copy, "funnel_today_label", "Today")} stages={stages} mode="today" copy={copy} /><Funnel title={fallback(copy, "funnel_month_label", "This month")} stages={stages} mode="mtd" copy={copy} /></div>{diagnostics.length > 0 && <div className="funnel-signals">{diagnostics.map((diagnostic) => <p className={diagnostic.status === "not-working" ? "signal-issue" : "signal-positive"} data-diagnostic-status={diagnostic.status} data-mismatch-id={diagnostic.mismatchId} key={diagnostic.stageLabel}><strong>{diagnostic.status === "not-working" ? fallback(copy, "funnel_not_working", "Not working today") : fallback(copy, "funnel_working", "Working today")} - {diagnostic.stageLabel}</strong><span>{diagnostic.reason}</span>{diagnostic.nextAction && <span><b>{fallback(copy, "funnel_action", "Action")}</b> - {diagnostic.nextAction}</span>}{diagnostic.accountableOwner && <span><b>{fallback(copy, "funnel_owner", "Owner")}</b> - {diagnostic.accountableOwner}</span>}{diagnostic.forwardCmAtRisk24h && <span><b>{fallback(copy, "funnel_cm_risk", "CM at risk in 24 hours")}</b> - {diagnostic.forwardCmAtRisk24h}</span>}</p>)}</div>}</div>
}
