import { NO_DATA, type MismatchInput, type RootCauseAnalysis } from "@/lib/allocation-types"

const review = { status: "Evidence-backed authored", reviewedBy: "Operating review", reviewedAt: "2026-07-15" } as const

function analysis(whys: RootCauseAnalysis["whys"], rootCause: string, recommendedSolution: string, evidenceReferences: string[]): RootCauseAnalysis {
  return { whys, rootCause, recommendedSolution, evidenceReferences, review }
}

/**
 * Illustrative operating data for the Operating Allocation Engine.
 * Theatre, Studio, SKU and owner names reuse the approved ops model; the five
 * forward-CM values reuse the approved constraint impacts (₹4.4L, ₹2.86L, ₹1.82L,
 * ₹96k, ₹72k). Every fallback or derived field is labelled. Nothing here feeds the
 * CM Trajectory or operating spine.
 */

/** Shram Park broker/property options, used to demonstrate the 2km + 24h eligibility rule. */
export type SupplyOption = {
  id: string
  theatre: string
  studio: string
  factory: string
  distanceKm: number
  responseHours: number
  availableByAt: string
  requiredByAt: string
}

export const supplyOptions: SupplyOption[] = [
  { id: "opt-hosur", theatre: "Wellington (Karnataka)", studio: "Hosur 01", factory: "Hosur", distanceKm: 1.4, responseHours: 9, availableByAt: "2026-07-16", requiredByAt: "2026-07-16" },
  { id: "opt-chakan", theatre: "Deccan (Pune)", studio: "Chakan 04", factory: "Chakan", distanceKm: 2.6, responseHours: 19, availableByAt: "2026-07-18", requiredByAt: "2026-07-18" },
  { id: "opt-sriperumbudur", theatre: "Coromandel (Tamil Nadu)", studio: "Sriperumbudur 02", factory: "Sriperumbudur", distanceKm: 1.8, responseHours: 27, availableByAt: "2026-07-17", requiredByAt: "2026-07-17" },
]

export const mismatchInputs: MismatchInput[] = [
  {
    id: "m-fono-idle-chakan",
    domain: "FONO",
    mismatchType: "idle-capacity",
    theatre: "Deccan (Pune)",
    where: "Chakan 04",
    label: "Live Nests idle without named demand",
    joinKey: { theatreId: "Deccan (Pune)", studioId: "Chakan 04", dateBucket: "2026-07-13" },
    demandQty: 0,
    supplyQty: 128,
    gapQty: 128,
    gapUnit: "Nests",
    ageHours: 120,
    thresholdHours: 48,
    deadlineAt: "16:00 IST",
    forwardCmAtRisk24h: 440000,
    recoverableShare: 0.6,
    confidence: "High",
    sourceUpdatedAt: "13:40 IST",
    sourceLabel: "FONO occupancy ledger (illustrative)",
    accountableOwner: "Demand JCO",
    actionStatus: "Detected",
    actionTemplateId: "fono-idle",
    laneTarget: { screen: "Living", subsection: "fono" },
    evidence: ["128 live Nests unoccupied", "No named enterprise requirement", "Idle 5 days against 48h threshold"],
    rootCauseAnalysis: analysis(
      ["128 live Nests are unoccupied.", "No named enterprise requirement is linked to the available Nests.", "The capacity has remained unmatched for five days.", "The 48-hour idle threshold passed without a named demand match.", "Evidence gap: the current ledger does not establish why demand was not named or matched."],
      "Available capacity has no named enterprise demand linked to it; the reason for the missing match is not evidenced.",
      "Assign the Demand JCO to verify the missing demand link, name a requirement or reallocate the 128 Nests, and record the reason for the failed match.",
      ["128 live Nests unoccupied", "No named enterprise requirement", "Idle 5 days against 48h threshold"],
    ),
  },
  {
    id: "m-sram-shortfall-sriperumbudur",
    domain: "Shram Park",
    mismatchType: "shortfall",
    theatre: "Coromandel (Tamil Nadu)",
    where: "Sriperumbudur 02",
    label: "No viable supply inside SLA for named demand",
    joinKey: { theatreId: "Coromandel (Tamil Nadu)", studioId: "Sriperumbudur 02", factoryId: "Sriperumbudur", demandBatchId: "batch-cor-282", requiredByAt: "2026-07-17" },
    demandQty: 282,
    supplyQty: 0,
    gapQty: 282,
    gapUnit: "Nests",
    ageHours: 27,
    thresholdHours: 24,
    deadlineAt: "17 Jul",
    forwardCmAtRisk24h: 286000,
    recoverableShare: 0.5,
    confidence: "Medium",
    sourceUpdatedAt: "13:20 IST",
    sourceLabel: "Shram Park sourcing board (illustrative)",
    accountableOwner: "Supply JCO",
    actionStatus: "Detected",
    actionTemplateId: "sram-shortfall",
    laneTarget: { screen: "Living", subsection: "Supply" },
    evidence: ["Nearest option 1.8km but responded at 27h", "Breaches 24h sourcing SLA", "0 eligible Nests within 2km"],
    rootCauseAnalysis: analysis(
      ["Named demand for 282 Nests has no eligible supply.", "The nearest option is inside 2km but responded after 27 hours.", "A 27-hour response breaches the 24-hour sourcing SLA.", "The breached response window makes the option ineligible, leaving zero eligible Nests.", "Evidence gap: the sourcing board does not state why the response exceeded 24 hours."],
      "The only nearby option missed the 24-hour response SLA; the delay mechanism is not evidenced.",
      "Escalate a replacement option now and review the broker response trail to identify and remove the specific cause of the three-hour SLA breach.",
      ["Nearest option 1.8km but responded at 27h", "Breaches 24h sourcing SLA", "0 eligible Nests within 2km"],
    ),
  },
  {
    id: "m-ess-stockout-hosur",
    domain: "Essentials",
    mismatchType: "stockout",
    theatre: "Wellington (Karnataka)",
    where: "Hosur 01",
    label: "High-repeat SKU below safety stock",
    joinKey: { theatreId: "Wellington (Karnataka)", studioId: "Hosur 01", skuId: "shampoo-sachet", dateBucket: "2026-07-13" },
    demandQty: 760,
    supplyQty: 60,
    gapQty: 700,
    gapUnit: "units",
    ageHours: 6,
    thresholdHours: 8,
    deadlineAt: "18:00",
    // Basis: 700 expected units lost × ₹260 Essentials CM per unit = ₹1.82L (see essentialsStockoutCm).
    forwardCmAtRisk24h: 182000,
    recoverableShare: 0.7,
    confidence: "High",
    sourceUpdatedAt: "13:55 IST",
    sourceLabel: "Essentials fill ledger (illustrative)",
    accountableOwner: "EAE + supplier",
    actionStatus: "Detected",
    actionTemplateId: "ess-stockout",
    laneTarget: { screen: "Essentials" },
    evidence: ["Days cover 0.8 against 1.0 safety", "Fill rate 81% (< 90%)", "700 units lost × ₹260 CM/unit"],
    rootCauseAnalysis: analysis(
      ["The high-repeat SKU is below safety stock.", "Available supply is 60 units against demand of 760 units.", "Days cover is 0.8 against the 1.0 safety level.", "The 81% fill rate is below the 90% threshold.", "Evidence gap: the fill ledger does not identify whether replenishment timing, supplier quantity, or demand variance caused the shortfall."],
      "Inventory is below the recorded safety level, but the upstream cause of the replenishment shortfall is not evidenced.",
      "Trigger replenishment for the 700-unit gap, then reconcile purchase order, supplier fill, and demand variance before changing the safety-stock rule.",
      ["Days cover 0.8 against 1.0 safety", "Fill rate 81% (< 90%)", "700 units lost × ₹260 CM/unit"],
    ),
    skuLabel: "Shampoo sachet",
  },
  {
    id: "m-ess-deadstock-chakan",
    domain: "Essentials",
    mismatchType: "dead-stock",
    theatre: "Deccan (Pune)",
    where: "Chakan 04",
    label: "Slow SKU accruing carrying loss",
    joinKey: { theatreId: "Deccan (Pune)", studioId: "Chakan 04", skuId: "work-footwear", dateBucket: "2026-07-13" },
    demandQty: 40,
    supplyQty: 480,
    gapQty: 440,
    gapUnit: "units",
    ageHours: 60,
    thresholdHours: 72,
    deadlineAt: "Day close",
    // Basis: 480 units × ₹200 expected markdown/carrying loss = ₹96k (see essentialsDeadStockCm).
    forwardCmAtRisk24h: 96000,
    recoverableShare: 0.4,
    confidence: "Medium",
    sourceUpdatedAt: "12:50 IST",
    sourceLabel: "Essentials inventory ageing (illustrative)",
    accountableOwner: "EAE",
    actionStatus: "Detected",
    actionTemplateId: "ess-deadstock",
    laneTarget: { screen: "Essentials" },
    evidence: ["Days cover 5.0", "Attach 2%", "Inventory aged 34 days"],
    rootCauseAnalysis: analysis(
      ["Work footwear inventory is accruing carrying loss.", "Supply exceeds recorded demand by 440 units.", "The SKU has only 2% attach and 5.0 days of cover.", "Inventory has aged for 34 days without sufficient movement.", "Evidence gap: the ageing ledger does not establish whether buying quantity, assortment, placement, or promotion caused low movement."],
      "Inventory has remained above demand for 34 days while attach is 2%; the upstream overstock cause is not evidenced.",
      "Reallocate or markdown the aged 440-unit excess, then audit the buy quantity and attach funnel before placing the next order.",
      ["Days cover 5.0", "Attach 2%", "Inventory aged 34 days"],
    ),
    skuLabel: "Work footwear",
    agedDays: 34,
  },
  {
    id: "m-fono-activation-noida",
    domain: "FONO",
    mismatchType: "idle-capacity",
    theatre: "Rajputana (NCR)",
    where: "Noida 01",
    label: "Contracted Members await activation",
    joinKey: { theatreId: "Rajputana (NCR)", studioId: "Noida 01", dateBucket: "2026-07-13" },
    demandQty: 32,
    supplyQty: 64,
    gapQty: 32,
    gapUnit: "Nests",
    ageHours: 44,
    thresholdHours: 48,
    deadlineAt: "15 Jul",
    forwardCmAtRisk24h: 72000,
    recoverableShare: 0.5,
    confidence: "Medium",
    sourceUpdatedAt: "13:30 IST",
    sourceLabel: "FONO activation queue (illustrative)",
    accountableOwner: "Operations lead",
    actionStatus: "Assigned",
    actionTemplateId: "fono-idle",
    laneTarget: { screen: "Living", subsection: "fono" },
    evidence: ["32 contracted Members not activated", "64 Nests live", "Idle 1 day against 48h threshold"],
    rootCauseAnalysis: analysis(
      ["Thirty-two contracted Members are not activated.", "Live capacity exists for 64 Nests.", "The activation queue therefore has demand and capacity but an incomplete activation step.", "The item has been idle for one day and is approaching the 48-hour threshold.", "Evidence gap: the queue does not record which activation dependency is incomplete."],
      "Contracted demand has not completed activation despite available capacity; the blocking activation dependency is not recorded.",
      "Contact the 32 Members, capture the incomplete activation dependency for each case, and clear or assign every verified blocker before the threshold.",
      ["32 contracted Members not activated", "64 Nests live", "Idle 1 day against 48h threshold"],
    ),
  },
  {
    id: "m-ess-dataquality-sriperumbudur",
    domain: "Essentials",
    mismatchType: "stockout",
    theatre: "Coromandel (Tamil Nadu)",
    where: "Sriperumbudur 02",
    label: "Fill and CM inputs missing for SKU",
    joinKey: { theatreId: "Coromandel (Tamil Nadu)", studioId: "Sriperumbudur 02", skuId: "detergent-bar", dateBucket: "2026-07-13" },
    demandQty: NO_DATA,
    supplyQty: NO_DATA,
    gapQty: NO_DATA,
    gapUnit: "units",
    ageHours: 30,
    thresholdHours: 8,
    deadlineAt: "18:00",
    forwardCmAtRisk24h: NO_DATA,
    recoverableShare: 0.5,
    confidence: "Low",
    sourceUpdatedAt: "Yesterday 14:00 IST",
    sourceLabel: "Essentials fill ledger (stale · illustrative)",
    accountableOwner: "Finance analyst",
    actionStatus: "Detected",
    actionTemplateId: "ess-stockout",
    laneTarget: { screen: "Essentials" },
    evidence: ["Fill rate not posted since yesterday", "CM per unit unavailable", "Treated as data-quality exception, not zero demand"],
    rootCauseAnalysis: analysis(
      ["The SKU cannot be assessed for fill or CM risk.", "Demand, supply, and CM per unit are missing rather than zero.", "The fill rate has not been posted since yesterday.", "The stale source prevents the engine from calculating a reliable gap or priority score.", "Evidence gap: the ledger does not identify whether ingestion, posting, or source capture failed."],
      "The Essentials fill ledger is stale and missing required values; the specific data-pipeline failure is not evidenced.",
      "Restore and validate demand, supply, fill, and CM inputs, then inspect the posting and ingestion trail before ranking this SKU as an operating stockout.",
      ["Fill rate not posted since yesterday", "CM per unit unavailable", "Treated as data-quality exception, not zero demand"],
    ),
    skuLabel: "Detergent bar",
  },
  {
    id: "m-sram-resolved-hosur",
    domain: "Shram Park",
    mismatchType: "shortfall",
    theatre: "Wellington (Karnataka)",
    where: "Hosur 01",
    label: "Eligible supply matched to named demand",
    joinKey: { theatreId: "Wellington (Karnataka)", studioId: "Hosur 01", factoryId: "Hosur", demandBatchId: "batch-wel-150", requiredByAt: "2026-07-16" },
    demandQty: 150,
    supplyQty: 150,
    gapQty: 0,
    gapUnit: "Nests",
    ageHours: 9,
    thresholdHours: 24,
    deadlineAt: "16 Jul",
    forwardCmAtRisk24h: 150000,
    recoverableShare: 0.6,
    confidence: "High",
    sourceUpdatedAt: "13:05 IST",
    sourceLabel: "Shram Park sourcing board (illustrative)",
    accountableOwner: "Supply JCO",
    actionStatus: "Resolved",
    actionTemplateId: "sram-shortfall",
    laneTarget: { screen: "Living", subsection: "Supply" },
    evidence: ["Option 1.4km within 2km", "Responded in 9h within SLA", "150 Nests matched and confirmed"],
    rootCauseAnalysis: analysis(
      ["The named demand required 150 Nests.", "An option was available 1.4km away.", "The option responded in nine hours, inside the 24-hour SLA.", "All 150 Nests were matched and confirmed.", "No unresolved root cause remains in the current evidence; retain this chain as a positive control."],
      "No active mismatch remains because nearby supply responded within SLA and covered the named demand.",
      "Keep the confirmed match under normal monitoring and reuse the eligible-supply response pattern where comparable demand appears.",
      ["Option 1.4km within 2km", "Responded in 9h within SLA", "150 Nests matched and confirmed"],
    ),
  },
  {
    id: "m-ess-resolved-recharge-sriperumbudur",
    domain: "Essentials",
    mismatchType: "stockout",
    theatre: "Coromandel (Tamil Nadu)",
    where: "Sriperumbudur 02",
    label: "Recharge availability and repeat ahead of plan",
    joinKey: { theatreId: "Coromandel (Tamil Nadu)", studioId: "Sriperumbudur 02", skuId: "mobile-recharge", dateBucket: "2026-07-13" },
    demandQty: 164,
    supplyQty: 164,
    gapQty: 0,
    gapUnit: "units",
    ageHours: 0,
    thresholdHours: 8,
    deadlineAt: "Day close",
    forwardCmAtRisk24h: 0,
    recoverableShare: 1,
    confidence: "High",
    sourceUpdatedAt: "13:52 IST",
    sourceLabel: "Essentials fill ledger (illustrative)",
    accountableOwner: "Essentials Demand · Marketing",
    actionStatus: "Resolved",
    actionTemplateId: "ess-stockout",
    laneTarget: { screen: "Essentials" },
    evidence: ["100% fill", "D30 repeat 48%", "Attach 18%"],
    rootCauseAnalysis: analysis(
      ["Recharge availability is ahead of plan.", "Recorded demand and supply both equal 164 units.", "The SKU has achieved 100% fill.", "Repeat is 48% and attach is 18% in the current evidence.", "No unresolved root cause remains; the available data supports continued monitoring, not corrective action."],
      "No active mismatch remains because supply fully covers recorded demand and the current repeat and attach signals are positive.",
      "Maintain availability and monitor fill, repeat, and attach for regression before changing the current operating approach.",
      ["100% fill", "D30 repeat 48%", "Attach 18%"],
    ),
    skuLabel: "Mobile recharge",
  },
]

/** Identity only. Card diagnostics still resolve the record through the Allocation Engine. */
export function mismatchContextById(id: string) {
  const input = mismatchInputs.find((item) => item.id === id)
  if (!input) throw new Error(`Unknown mismatch context: ${id}`)
  return { domain: input.domain, joinKey: input.joinKey }
}
