import type { ActionLogEntry, ActionType } from "@/lib/action-log"
import type { ActionStatus } from "@/lib/allocation-types"
import type { ExecutionAction } from "@/lib/execution-control"

type LogStep = [ActionType, ActionStatus | null, ActionStatus, string, string | null, string?]

function history(actionId: string, steps: LogStep[]): ActionLogEntry[] {
  return steps.map(([actionType, previousStatus, newStatus, executedAt, actorId, note], index) => ({
    id: `log-${actionId}-${index + 1}`,
    queue_item_id: actionId,
    actor_id: actorId,
    action_type: actionType,
    previous_status: previousStatus,
    new_status: newStatus,
    executed_at: executedAt,
    ...(note ? { note } : {}),
  }))
}

const monthlyReview = {
  meetingId: "monthly-operations-review",
  meetingLabel: "Monthly Operations Review",
  meetingDate: "2026-07-01T09:00:00+05:30",
  nextMeetingDue: "2026-07-15T09:00:00+05:30",
} as const

/** Illustrative execution-control data. No live meeting, WhatsApp or Google Sheets feed is connected yet. */
export const executionActions: ExecutionAction[] = [
  {
    id: "exec-chakan-demand",
    source: "system_detected",
    title: "Assign named Member demand to Chakan 04's 128 live Nests.",
    owner: "Vikram Singh",
    team: "FONO Demand",
    theatre: "Deccan (Pune)",
    committedBy: "Allocation engine",
    dueAt: "2026-07-14T18:00:00+05:30",
    evidence: [],
    affectedMembers: 128,
    expectedMetric: { key: "members_activated", label: "Members activated", direction: "up", checkWindowDays: 7, baselineValue: 0, actualValue: null, unit: "Members", memberSignal: { label: "Move-in satisfaction", baselineValue: 0, actualValue: null, unit: "% positive" } },
    actionLog: history("exec-chakan-demand", [
      ["detect", null, "Detected", "2026-07-13T10:00:00+05:30", null],
      ["assign", "Detected", "Assigned", "2026-07-13T12:00:00+05:30", "vikram-singh"],
    ]),
    route: { screen: "Living", subsection: "fono" },
    mismatchId: "m-fono-idle-chakan",
    meetingId: null,
    meetingLabel: null,
    meetingDate: null,
    decisionText: null,
    nextMeetingDue: null,
  },
  {
    id: "exec-footwear-ageing",
    source: "meeting_commitment",
    title: "Reprice, transfer or return Work footwear at Chakan 04.",
    owner: "Neha Kulkarni",
    team: "Essentials Supply",
    theatre: "Deccan (Pune)",
    committedBy: "Neha Kulkarni",
    dueAt: "2026-07-11T17:00:00+05:30",
    evidence: ["Price review worksheet submitted"],
    affectedMembers: 42,
    expectedMetric: { key: "footwear_sell_through", label: "14-day footwear sell-through", direction: "up", checkWindowDays: 14, baselineValue: 2, actualValue: null, unit: "%", memberSignal: { label: "Members finding the right size", baselineValue: 61, actualValue: null, unit: "% positive" } },
    actionLog: history("exec-footwear-ageing", [
      ["agree", null, "Agreed", "2026-07-01T10:14:00+05:30", "neha-kulkarni", "Reprice the ageing footwear before the next review."],
      ["assign", "Agreed", "Assigned", "2026-07-01T10:20:00+05:30", "neha-kulkarni"],
      ["resolve", "Assigned", "Resolved", "2026-07-11T11:20:00+05:30", "neha-kulkarni", "Price review completed."],
      ["close", "Resolved", "Closed", "2026-07-11T12:00:00+05:30", "neha-kulkarni", "Executor marked the commitment closed."],
    ]),
    route: { screen: "Essentials" },
    mismatchId: "m-ess-deadstock-chakan",
    ...monthlyReview,
    decisionText: "Reprice the ageing footwear and validate sell-through at the next review.",
  },
  {
    id: "exec-hosur-hold",
    source: "system_detected",
    title: "Hold 150 matched Nests for Hosur demand through activation.",
    owner: "Nisha Patel",
    team: "Shram Park Supply",
    theatre: "Wellington (Karnataka)",
    committedBy: "Allocation engine",
    dueAt: "2026-07-14T16:00:00+05:30",
    evidence: ["Hold reference SP-HSR-150", "150 Nests confirmed"],
    affectedMembers: 150,
    expectedMetric: { key: "activation_readiness", label: "Nests ready for activation", direction: "up", checkWindowDays: 1, baselineValue: 100, actualValue: null, unit: "Nests", memberSignal: { label: "Members activated without delay", baselineValue: 67, actualValue: null, unit: "%" } },
    actionLog: history("exec-hosur-hold", [
      ["detect", null, "Detected", "2026-07-13T09:00:00+05:30", null],
      ["assign", "Detected", "Assigned", "2026-07-13T09:20:00+05:30", "nisha-patel"],
      ["resolve", "Assigned", "Resolved", "2026-07-14T09:45:00+05:30", "nisha-patel"],
      ["close", "Resolved", "Closed", "2026-07-14T10:00:00+05:30", "nisha-patel"],
      ["verify", "Closed", "Verified", "2026-07-15T12:30:00+05:30", "wellington-checker", "Evidence verified independently."],
    ]),
    route: { screen: "Living", subsection: "supply" },
    meetingId: null,
    meetingLabel: null,
    meetingDate: null,
    decisionText: null,
    nextMeetingDue: null,
  },
  {
    id: "exec-essentials-recharge",
    source: "meeting_commitment",
    title: "Keep mobile recharge availability at 100% in Sriperumbudur 02.",
    owner: "Lakshmi S",
    team: "Essentials Supply",
    theatre: "Coromandel (Tamil Nadu)",
    committedBy: "Lakshmi S",
    dueAt: "2026-07-10T18:00:00+05:30",
    evidence: ["Availability ledger 10 Jul", "Studio fill proof"],
    affectedMembers: 86,
    expectedMetric: { key: "recharge_availability", label: "Recharge availability", direction: "up", checkWindowDays: 3, baselineValue: 92, actualValue: 100, unit: "%", memberSignal: { label: "Successful Member purchases", baselineValue: 79, actualValue: 100, unit: "%" } },
    actionLog: history("exec-essentials-recharge", [
      ["agree", null, "Agreed", "2026-07-01T10:30:00+05:30", "lakshmi-s", "Restore recharge availability to 100%."],
      ["assign", "Agreed", "Assigned", "2026-07-01T10:32:00+05:30", "lakshmi-s"],
      ["resolve", "Assigned", "Resolved", "2026-07-10T16:42:00+05:30", "lakshmi-s"],
      ["close", "Resolved", "Closed", "2026-07-10T16:50:00+05:30", "lakshmi-s"],
      ["verify", "Closed", "Verified", "2026-07-10T17:05:00+05:30", "essentials-checker"],
    ]),
    route: { screen: "Essentials" },
    ...monthlyReview,
    decisionText: "Restore mobile recharge availability to 100% and hold it for three days.",
  },
  {
    id: "exec-kyc-close",
    source: "meeting_commitment",
    title: "Complete KYC for two agreed FONO Studios.",
    owner: "Priya Menon",
    team: "FONO Supply",
    theatre: "Rajputana (NCR)",
    committedBy: "Priya Menon",
    dueAt: "2026-07-12T15:00:00+05:30",
    evidence: ["KYC references FONO-214 and FONO-218"],
    affectedMembers: 0,
    expectedMetric: { key: "new_live_nests", label: "New live Nests", direction: "up", checkWindowDays: 7, baselineValue: 0, actualValue: null, unit: "Nests", memberSignal: { label: "Members placed in new Nests", baselineValue: 0, actualValue: null, unit: "Members" } },
    actionLog: history("exec-kyc-close", [
      ["agree", null, "Agreed", "2026-07-01T10:50:00+05:30", "priya-menon", "Complete both KYC files."],
      ["assign", "Agreed", "Assigned", "2026-07-01T10:52:00+05:30", "priya-menon"],
      ["resolve", "Assigned", "Resolved", "2026-07-12T13:40:00+05:30", "priya-menon"],
      ["close", "Resolved", "Closed", "2026-07-12T13:50:00+05:30", "priya-menon"],
      ["verify", "Closed", "Verified", "2026-07-12T14:10:00+05:30", "rajputana-checker"],
    ]),
    route: { screen: "Living", subsection: "fono" },
    ...monthlyReview,
    decisionText: "Complete KYC for both agreed Studios before 12 July.",
  },
  {
    id: "exec-hosur-shampoo",
    source: "system_detected",
    title: "Repool shampoo sachets to Hosur 01 before the evening shift.",
    owner: "Rohan Iyer",
    team: "Essentials Supply",
    theatre: "Wellington (Karnataka)",
    committedBy: "Allocation engine",
    dueAt: "2026-07-08T18:00:00+05:30",
    evidence: ["Inbound GRN HSR-441", "Studio receipt"],
    affectedMembers: 64,
    expectedMetric: { key: "shampoo_fill_rate", label: "Shampoo fill rate", direction: "up", checkWindowDays: 7, baselineValue: 81, actualValue: 79, unit: "%", memberSignal: { label: "Members finding shampoo in stock", baselineValue: 76, actualValue: 73, unit: "% positive" } },
    actionLog: history("exec-hosur-shampoo", [
      ["detect", null, "Detected", "2026-07-07T09:00:00+05:30", null],
      ["assign", "Detected", "Assigned", "2026-07-07T09:10:00+05:30", "rohan-iyer"],
      ["resolve", "Assigned", "Resolved", "2026-07-08T12:20:00+05:30", "rohan-iyer"],
      ["close", "Resolved", "Closed", "2026-07-08T12:40:00+05:30", "rohan-iyer"],
      ["verify", "Closed", "Verified", "2026-07-08T13:00:00+05:30", "essentials-checker"],
    ]),
    route: { screen: "Essentials" },
    mismatchId: "m-ess-stockout-hosur",
    meetingId: null,
    meetingLabel: null,
    meetingDate: null,
    decisionText: null,
    nextMeetingDue: null,
  },
  {
    id: "exec-manesar-handoff",
    source: "meeting_commitment",
    title: "Confirm the Manesar demand hand-off to the activation owner.",
    owner: "Aditi Rao",
    team: "Shram Park Demand",
    theatre: "Rajputana (NCR)",
    committedBy: "Aditi Rao",
    dueAt: "2026-07-10T13:00:00+05:30",
    evidence: ["Handoff reference MAN-300", "Activation owner accepted"],
    affectedMembers: 300,
    expectedMetric: { key: "confirmed_handoffs", label: "Members with confirmed hand-off", direction: "up", checkWindowDays: 3, baselineValue: 0, actualValue: 300, unit: "Members", memberSignal: { label: "Members contacted within 24 hours", baselineValue: 0, actualValue: 287, unit: "Members" } },
    actionLog: history("exec-manesar-handoff", [
      ["agree", null, "Agreed", "2026-07-01T11:10:00+05:30", "aditi-rao", "Complete the hand-off to the named activation owner."],
      ["assign", "Agreed", "Assigned", "2026-07-01T11:12:00+05:30", "aditi-rao"],
      ["resolve", "Assigned", "Resolved", "2026-07-10T11:50:00+05:30", "aditi-rao"],
      ["close", "Resolved", "Closed", "2026-07-10T12:00:00+05:30", "aditi-rao"],
      ["verify", "Closed", "Verified", "2026-07-10T12:15:00+05:30", "rajputana-checker"],
    ]),
    route: { screen: "Living", subsection: "demand" },
    ...monthlyReview,
    decisionText: "Name the activation owner and complete the Manesar hand-off.",
  },
  {
    id: "exec-sip-radius-reject",
    source: "meeting_commitment",
    title: "Use the 2.5 km Sriperumbudur option despite the 2 km rule.",
    owner: "Meera Nair",
    team: "Shram Park Demand",
    theatre: "Coromandel (Tamil Nadu)",
    committedBy: "Meeting chair",
    dueAt: "2026-07-12T12:00:00+05:30",
    evidence: ["Dismissed: outside the approved radius"],
    affectedMembers: 0,
    expectedMetric: { key: "radius_exceptions", label: "Approved radius exceptions", direction: "down", checkWindowDays: 1, baselineValue: 1, actualValue: 0, unit: "Exceptions" },
    actionLog: history("exec-sip-radius-reject", [
      ["agree", null, "Agreed", "2026-07-01T11:30:00+05:30", "meeting-chair", "Review the radius exception."],
      ["dismiss", "Agreed", "Dismissed", "2026-07-02T09:00:00+05:30", "meera-nair", "Outside the approved 2 km radius."],
    ]),
    route: { screen: "Living", subsection: "supply" },
    ...monthlyReview,
    decisionText: "Review whether the 2.5 km exception should be approved.",
  },
]

export const EXECUTION_REPORT_AS_OF = "2026-07-15T14:00:00+05:30"
export const EXECUTION_BLOCK_START = "2026-07-15T12:00:00+05:30"
